---
abstract: 'Perlbal plugin for Server::Starter support'
author:
  - 'Hiroshi Sakai <ziguzagu@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perlbal-Plugin-ServerStarter
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Perlbal: 0
  Server::Starter: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/ziguzagu/Perlbal-Plugin-ServerStarter.git
version: 0.03
x_authority: ZIGUZAGU
